/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddQuestionForm: typeof import('./src/components/Question/AddQuestionForm.vue')['default']
    AnalysisForm: typeof import('./src/components/Course/AnalysisForm.vue')['default']
    BarChart: typeof import('./src/components/Statistics/BarChart.vue')['default']
    BaseAlert: typeof import('./src/components/Base/BaseAlert.vue')['default']
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    ClassDetail: typeof import('./src/components/Course/ClassDetail.vue')['default']
    ClassItem: typeof import('./src/components/Course/ClassItem.vue')['default']
    CourseInfoItem: typeof import('./src/components/Course/CourseInfoItem.vue')['default']
    CreateCourseForm: typeof import('./src/components/Course/CreateCourseForm.vue')['default']
    DistributionForm: typeof import('./src/components/Course/DistributionForm.vue')['default']
    DoughnutChart: typeof import('./src/components/Statistics/DoughnutChart.vue')['default']
    FileInput: typeof import('./src/components/Base/FileInput.vue')['default']
    ImportCard: typeof import('./src/components/Base/ImportCard.vue')['default']
    LabContribution: typeof import('./src/components/Course/LabContribution.vue')['default']
    LabItem: typeof import('./src/components/Course/LabItem.vue')['default']
    OverviewChart: typeof import('./src/components/Statistics/OverviewChart.vue')['default']
    PerformanceChart: typeof import('./src/components/Statistics/PerformanceChart.vue')['default']
    RecentCourseItem: typeof import('./src/components/Course/RecentCourseItem.vue')['default']
    RecentList: typeof import('./src/components/Course/RecentList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SubmissionForm: typeof import('./src/components/Course/SubmissionForm.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UploadSubmission: typeof import('./src/components/Base/UploadSubmission.vue')['default']
  }
}
